# test_md_doubleclick.ps1 — automated repro of the .md double-click
# flow with full process tracing.
#
# What it does:
#   1. Kills any running Obsidian / open_md_launcher / obs_watcher.
#   2. Clears the launcher's debug log and (optionally) the temp vault.
#   3. Snapshots running PIDs as a baseline.
#   4. Creates a fresh test .md (with a unique name) outside the vault.
#   5. Invokes ShellExecuteEx via Start-Process — the same code path
#      Explorer uses on a double-click. (Verified earlier: user's
#      actual double-clicks produced the same Obsidian launch behavior
#      we see from Start-Process here.)
#   6. Polls for ~5 s, capturing every new process whose name matches
#      Obsidian, open_md_launcher, obs_watcher, or cmd — with its full
#      command line and parent PID via Win32_Process.
#   7. Reads the launcher debug log + temp vault listing + Obsidian
#      workspace.json's active leaf.
#   8. Prints a structured verdict telling us exactly which stage
#      passed or failed.
#
# Usage:
#   .\test_md_doubleclick.ps1                  # default: fresh test file
#   .\test_md_doubleclick.ps1 -KeepVault       # don't wipe vault files
#   .\test_md_doubleclick.ps1 -KillObsidian:$false  # don't kill obsidian first

[CmdletBinding()]
param(
    [switch] $KeepVault,
    [switch] $KillObsidian = $true,
    [int]    $WaitSeconds = 6
)

$ErrorActionPreference = 'Stop'
$bs = [char]92

$Vault       = 'C:' + $bs + 'Users' + $bs + 'azt12' + $bs + 'Temp Obsidian Vault'
$LauncherLog = 'C:' + $bs + 'Users' + $bs + 'azt12' + $bs + 'open_md_launcher_debug.log'
$WatcherLog  = 'C:' + $bs + 'Users' + $bs + 'azt12' + $bs + 'obs_watcher_debug.log'
$TempRoot    = 'C:' + $bs + 'Users' + $bs + 'azt12' + $bs + 'OneDrive' + $bs + 'Documents' + $bs + 'Computing' + $bs + 'Temp'
$WatchNames  = @('Obsidian','open_md_launcher','obs_watcher','cmd','conhost')

function Section($title) {
    Write-Host ''
    Write-Host ('=== ' + $title + ' ===') -ForegroundColor Cyan
}

# ── Stage 1: reset state ────────────────────────────────────────────
Section 'Stage 1 — reset state'

if ($KillObsidian) {
    foreach ($n in @('Obsidian','open_md_launcher','obs_watcher')) {
        $procs = Get-Process -Name $n -ErrorAction SilentlyContinue
        if ($procs) {
            Write-Host ("Killing " + $n + " (" + $procs.Count + " procs)")
            $procs | Stop-Process -Force -ErrorAction SilentlyContinue
        }
    }
    Start-Sleep -Milliseconds 800
}

if (Test-Path -LiteralPath $LauncherLog) {
    Remove-Item -LiteralPath $LauncherLog -Force
    Write-Host 'Cleared launcher debug log'
}

if (-not $KeepVault) {
    if (Test-Path -LiteralPath $Vault) {
        Get-ChildItem -LiteralPath $Vault -File -ErrorAction SilentlyContinue |
            Where-Object { $_.Name -like '*.md' } |
            ForEach-Object {
                Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue
                Write-Host ('Removed vault file: ' + $_.Name)
            }
    }
}

# ── Stage 2: create a fresh test .md ────────────────────────────────
Section 'Stage 2 — create test .md'

$stamp = (Get-Date -Format 'HHmmss')
$testName = 'dctest_' + $stamp + '.md'
$testPath = $TempRoot + $bs + $testName
$body = @"
# Double-Click Test $stamp

Test file generated by test_md_doubleclick.ps1 at $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss').
If you see this content inside Obsidian, the entire .md double-click
flow is working end-to-end.
"@
Set-Content -LiteralPath $testPath -Value $body -Encoding UTF8
Write-Host ('Created: ' + $testPath)

# ── Stage 3: baseline PIDs ──────────────────────────────────────────
Section 'Stage 3 — baseline PID snapshot'

$baseline = @{}
foreach ($n in $WatchNames) {
    $baseline[$n] = (Get-Process -Name $n -ErrorAction SilentlyContinue |
                     ForEach-Object { $_.Id })
    Write-Host ($n + ': ' + ((@($baseline[$n]) -join ',')))
}

# ── Stage 4: ShellExecute the .md (Explorer-equivalent code path) ───
Section 'Stage 4 — ShellExecute the .md (simulates Explorer double-click)'

$psi = New-Object System.Diagnostics.ProcessStartInfo
$psi.FileName       = $testPath
$psi.UseShellExecute = $true
$null = [System.Diagnostics.Process]::Start($psi)
Write-Host ('Fired ShellExecuteEx open on: ' + $testPath)
Write-Host ('Polling for ' + $WaitSeconds + ' s for new processes...')

# ── Stage 5: collect new processes + command lines via WMI ──────────
$endTime  = (Get-Date).AddSeconds($WaitSeconds)
$captured = New-Object System.Collections.Generic.List[object]
$seenPids = New-Object System.Collections.Generic.HashSet[int]

while ((Get-Date) -lt $endTime) {
    foreach ($n in $WatchNames) {
        $curr = Get-Process -Name $n -ErrorAction SilentlyContinue
        foreach ($p in $curr) {
            if ($baseline[$n] -contains $p.Id) { continue }
            if ($seenPids.Contains($p.Id)) { continue }
            $seenPids.Add($p.Id) | Out-Null
            $wmi = Get-CimInstance Win32_Process -Filter ("ProcessId = " + $p.Id) -ErrorAction SilentlyContinue
            $captured.Add([pscustomobject]@{
                Name        = $n
                PID         = $p.Id
                ParentPID   = if ($wmi) { $wmi.ParentProcessId } else { $null }
                CommandLine = if ($wmi) { $wmi.CommandLine } else { '<unavailable>' }
                StartTime   = try { $p.StartTime } catch { Get-Date }
            })
        }
    }
    Start-Sleep -Milliseconds 200
}

Section 'Stage 5 — Captured processes'
if ($captured.Count -eq 0) {
    Write-Host 'NONE — no new processes detected.' -ForegroundColor Yellow
} else {
    foreach ($c in $captured) {
        Write-Host ('[' + $c.Name + ' pid=' + $c.PID + ' ppid=' + $c.ParentPID + ']')
        Write-Host ('  CMD: ' + $c.CommandLine) -ForegroundColor Gray
    }
}

# Resolve parent-PID lineage for Obsidian (who launched it?)
$obsidianProcs = $captured | Where-Object { $_.Name -eq 'Obsidian' }
if ($obsidianProcs) {
    Section 'Obsidian parent lineage'
    foreach ($o in $obsidianProcs) {
        $cur = $o.ParentPID
        while ($cur -and $cur -ne 0) {
            $p = Get-CimInstance Win32_Process -Filter ("ProcessId = " + $cur) -ErrorAction SilentlyContinue
            if (-not $p) { break }
            Write-Host ('  ppid=' + $p.ProcessId + ' name=' + $p.Name + '  cmd=' + $p.CommandLine)
            $cur = $p.ParentProcessId
            if ($cur -eq $p.ProcessId) { break }
        }
    }
}

# ── Stage 6: launcher debug log ─────────────────────────────────────
Section 'Stage 6 — launcher debug log'
if (Test-Path -LiteralPath $LauncherLog) {
    Get-Content -LiteralPath $LauncherLog
} else {
    Write-Host '(launcher debug log not created)' -ForegroundColor Yellow
}

# ── Stage 7: vault contents ─────────────────────────────────────────
Section 'Stage 7 — vault contents'
if (Test-Path -LiteralPath $Vault) {
    Get-ChildItem -LiteralPath $Vault | Select-Object Name, Length |
        Format-Table -AutoSize | Out-String | Write-Host
} else {
    Write-Host '(vault directory does not exist)' -ForegroundColor Yellow
}

# ── Stage 8: workspace.json active leaf ─────────────────────────────
Section 'Stage 8 — Obsidian workspace.json active leaf'
$ws = $Vault + $bs + '.obsidian' + $bs + 'workspace.json'
if (Test-Path -LiteralPath $ws) {
    $j = Get-Content -LiteralPath $ws -Raw | ConvertFrom-Json
    $activeId = $j.active
    function FindLeaf($node, $id) {
        if ($node.id -eq $id) { return $node }
        if ($node.children) {
            foreach ($c in $node.children) {
                $r = FindLeaf $c $id
                if ($r) { return $r }
            }
        }
        return $null
    }
    $leaf = $null
    foreach ($region in @('main','left','right')) {
        if ($j.$region) {
            $leaf = FindLeaf $j.$region $activeId
            if ($leaf) { break }
        }
    }
    if ($leaf) {
        Write-Host ('active leaf type:  ' + $leaf.state.type)
        Write-Host ('active leaf title: ' + $leaf.state.title)
        Write-Host ('active leaf file:  ' + $leaf.state.state.file)
    } else {
        Write-Host ('active id ' + $activeId + ' not found in main/left/right')
    }
    if ($j.lastOpenFiles) {
        Write-Host ('lastOpenFiles: ' + ($j.lastOpenFiles -join ', '))
    }
} else {
    Write-Host '(workspace.json absent — vault never opened)' -ForegroundColor Yellow
}

# ── Stage 9: verdict ────────────────────────────────────────────────
Section 'VERDICT'

$launcherRan = Test-Path -LiteralPath $LauncherLog
$fileInVault = $false
if (Test-Path -LiteralPath $Vault) {
    $fileInVault = (Get-ChildItem -LiteralPath $Vault -Filter '*.md' -ErrorAction SilentlyContinue |
                    Where-Object { $_.Name -match [Regex]::Escape($testName.Replace('.md','')) }) -ne $null
}
$obsidianLaunched = ($captured | Where-Object { $_.Name -eq 'Obsidian' }) -ne $null

# Check parent lineage to determine WHO launched Obsidian
$obsidianViaLauncher = $false
if ($obsidianProcs -and $captured | Where-Object { $_.Name -eq 'open_md_launcher' }) {
    $launcherPids = ($captured | Where-Object { $_.Name -eq 'open_md_launcher' }).PID
    foreach ($o in $obsidianProcs) {
        $cur = $o.ParentPID
        $depth = 0
        while ($cur -and $depth -lt 10) {
            if ($launcherPids -contains $cur) { $obsidianViaLauncher = $true; break }
            $p = Get-CimInstance Win32_Process -Filter ("ProcessId = " + $cur) -ErrorAction SilentlyContinue
            if (-not $p) { break }
            $cur = $p.ParentProcessId
            $depth++
        }
    }
}

$activeFile = $null
if (Test-Path -LiteralPath $ws) {
    $j = Get-Content -LiteralPath $ws -Raw | ConvertFrom-Json
    function FindLeaf2($node, $id) {
        if ($node.id -eq $id) { return $node }
        if ($node.children) {
            foreach ($c in $node.children) {
                $r = FindLeaf2 $c $id
                if ($r) { return $r }
            }
        }
        return $null
    }
    foreach ($region in @('main','left','right')) {
        if ($j.$region) {
            $leaf = FindLeaf2 $j.$region $j.active
            if ($leaf) { $activeFile = $leaf.state.state.file; break }
        }
    }
}

$pass = $true
Write-Host ('Launcher .exe ran?       ' + [bool]$launcherRan)  ; if (-not $launcherRan) { $pass = $false }
Write-Host ('File copied to vault?    ' + [bool]$fileInVault)  ; if (-not $fileInVault) { $pass = $false }
Write-Host ('Obsidian launched?       ' + [bool]$obsidianLaunched)
Write-Host ('Active file in vault:    ' + $activeFile)
$activeMatches = $activeFile -and ($testName -eq $activeFile)
if ($activeMatches) {
    Write-Host '  -> matches test file (PASS)' -ForegroundColor Green
} else {
    Write-Host '  -> does NOT match test file' -ForegroundColor Yellow
    $pass = $false
}

# ── Stage 10: cleanup — kill Obsidian + watcher so the user doesn't
# have to. The user has explicit standing approval to freely kill
# these between test iterations (2026-05-22).
Section 'Stage 10 — cleanup'
foreach ($n in @('Obsidian','obs_watcher','open_md_launcher')) {
    $p = Get-Process -Name $n -ErrorAction SilentlyContinue
    if ($p) {
        Write-Host ('Killing ' + $n + ' (' + $p.Count + ' procs)')
        $p | Stop-Process -Force -ErrorAction SilentlyContinue
    }
}
Start-Sleep -Milliseconds 600

Write-Host ''
if ($pass) {
    Write-Host 'OVERALL: PASS' -ForegroundColor Green
    exit 0
} else {
    Write-Host 'OVERALL: FAIL' -ForegroundColor Red
    exit 1
}
